application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      __APP_PACKAGE__:
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: 'nodejs:18'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true