extensions:
  dx/excshell/1:
    $include: src/dx-excshell-1/ext.config.yaml
configSchema:
  - title: "Open AI api key"
    type: "string"
    secret: true
    description: "please provide your open ai api key"
    envKey: "OPENAI_API_KEY"
  - title: "the dropdown"
    type: "string"
    description: "please provide your favorite color"
    enum:
      - "yellow"
      - "pink"
      - "blue"
      - "green"
      - "red"
    envKey: "MY_COLOR"
